### ISSUE TITLE
http:server[] 可以只 add 不 update 吗

### ISSUE THREAD

**Issue by SpaceTimee** [jxnkwlp/NginxConfigParser#14]
我的配置文件中原本就有一些 Server 块，我希望在此基础上添加一些 Server 块而不修改原本的 Server 块，但是 NginxConfigParser 使用 NginxConfig.Load().AddOrUpdate() 会优先修改原来配置文件中的 Server 块

我的建议是再添加一个不会修改原配置的 Add() 函数 (最推荐)，或者允许 Server[index] 的 index 为负数 (如果为负数就不修改只添加)，或者允许 index 不从 0 开始增加 (比如 index 为 100 时，第 0 到 99 的 server 就不会被修改)，这个功能我非常需要，能否添加一下这个功能

**Comment by jxnkwlp** [comment]
假设现在有1个 server 块， 需要添加 第二个，用 `config.AddOrUpdate("server[2]:root", "/var/wwwroot/server2");`  就可以了。 下标是下一个不存在的数字。

**Comment by SpaceTimee** [comment]
我项目中的 nginx 配置文件是用户可以自己编辑的，也就是说原本的配置文件中的 server 数量是不确定的

目前我只能通过计数配置文件中已有的 "server" 字符串数量来粗略作为新 server 的下标

**Comment by jxnkwlp** [comment]
可以加载 conf 文件后，获取到所有块
[    public IEnumerable<IToken> GetTokens() => _tokens;](https://github.com/jxnkwlp/NginxConfigParser/blob/56a7e6c292818d27000095a77a123c911573da18/NginxConfigParser/NginxConfig.cs#L91)

这样是可以知道这个文件内有多少 Server 块了。

**Comment by SpaceTimee** [comment]
好的，这样可以实现，谢谢了
