### ISSUE TITLE
How to add a group value

### ISSUE THREAD

**Issue by SpazCode153** [jxnkwlp/NginxConfigParser#2]
How does one add a group value?

For example a location block can specify a route like /api

location /api {

}

I couldn't find a way to do this so I added a bit of code to allow one to create a group and add a value afterwards, I can create a pull request for this if you'd like

**Comment by jxnkwlp** [comment]
``` cs
// add group
config.AddOrUpdate("http:server:location", "/api", true, comment: "new location");
// add value to group
config.AddOrUpdate("http:server:location:root", "/var/wwwroot"); 
```

output: 

```
    location  /api  { # new loaction
      root  /var/wwwroot;
    }
```

**Comment by SpazCode153** [comment]
Thanks jxnkwlp, sorry about my ignorance
