### ISSUE TITLE
How to add parameters with conditional expressions

### ISSUE THREAD

**Issue by jidesheng6** [jxnkwlp/NginxConfigParser#9]
Hello
Thank you very much for writing the Nginx parser, I would like to ask if I can use this tool to write configuration files with conditional expressions?
For example, I would like to write the following.
```c#
if($time_iso8061 ~ '(\d{4}-\d{2}-\d{2})'){
set $time $1;
}
access_log log/aceess-$time.log;

```
How should I write the code please

**Comment by jxnkwlp** [comment]
Sorry, now it unsupport conditional expressions. 

Maybe you can try use conditional expressions as `key`  .

For example
`.AddOrUpdate("if($time_iso8061 ~ '(\d{4}-\d{2}-\d{2})')", "")`

**Comment by jidesheng6** [comment]
![image](https://user-images.githubusercontent.com/25132549/174699128-1f7c7ec0-9acd-4c1c-b140-43654a63297c.png)
Thank you very much for your reply, I tried adding the above code and it doesn't seem to be working, but thank you very much!
